######################
# configuration file #
######################

---

species_list:
  - boxer1-E102
  - dingo1-E102
  - redfox-E102
  - dhole
  - wolf

species_info_list:

  - species: "boxer1-E102"
    Latin_name: "Canis_lupus_familiaris"
    family: "Canidae"
    Taxonomy_ID: 9615

  - species: "dingo1-E102"
    Latin_name: "Canis_lupus_dingo"
    family: "Canidae"
    Taxonomy_ID: 286419

  - species: "redfox-E102"
    Latin_name: "Vulpes_vulpes"
    family: "Canidae"
    Taxonomy_ID: 9627

  - species: "dhole"
    Latin_name: "Cuon_alpinus"
    family: "Canidae"
    Taxonomy_ID: 68730

  - species: "wolf"
    Latin_name: "Canis_lupus"
    family: "Canidae"
    Taxonomy_ID: 9612
